### ISSUE TITLE
Document OAuth scopes needed

### ISSUE THREAD

**Issue by mejedi** [voxmedia/github-action-slack-notify-build#10]
In addition to `chat:write` (kinda obvious), `channels:read` and `groups:read` are needed if `channel` is used instead of `channel_id`. Would be nice if documentation explicitly spelled that out.

**Comment by bonham000** [comment]
I'm also having a lot of trouble getting it to work, and currently receiving the error:

```
##[error]An API error occurred: missing_scope
```

I've tried adding several different scopes like the ones mentioned above but haven't solved it yet.

**Comment by iam-mhaseeb** [comment]
@mejedi's mentioned permissions worked for me! @bonham000 Have your tried reinstalling app after updating permissions?

**Comment by gjvoosten** [comment]
https://github.com/voxmedia/github-action-slack-notify-build/issues/9#issuecomment-583863180 mentions two more scopes (`channels:join` and `groups:write`). Can anyone verify what the complete & sufficient list should be?

**Comment by hollandz** [comment]
![Screen Shot 2020-06-11 at 6 46 12 PM](https://user-images.githubusercontent.com/7843944/84446621-e126e480-ac13-11ea-8e76-5b515b3ed403.png)

works for me after losing about an hour of development time troubleshooting this. Can you all add this to the documentation? Maybe the error response that's coming from the API could also include the full response? I believe the Slack failed response looks something like `{"ok":false,"error":"missing_scope","needed":"rtm:stream","provided":"identify,bot,channels:history,channels:read,team:read,users:read"}`

**Comment by jplhomer** [comment]
I've added required scopes to the README; if there are additional steps needed, please submit a PR.
