### ISSUE TITLE
##[error]An API error occurred: not_in_channel

### ISSUE THREAD

**Issue by radheyshyamjat** [voxmedia/github-action-slack-notify-build#15]
Run voxmedia/github-action-slack-notify-build@v1.1.1
  with:
    channel_id: C8KCLQDDF
    status: SUCCESS
    color: good
  env:
    SLACK_BOT_TOKEN: Here is token
(node:4050) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]An API error occurred: not_in_channel

**Comment by Geek-ubaid** [comment]
@radheyshyamjat any success on this thing?

**Comment by radheyshyamjat** [comment]
@Geek-ubaid yes when invite working fine
