### ISSUE TITLE
The action is not automatically inviting the bot to the channel

### ISSUE THREAD

**Issue by Geek-ubaid** [voxmedia/github-action-slack-notify-build#16]
The action is throwing the not_in_channel error because the app after installation is not invited to the channel. I have to manually invite the bot to the channel and then execute the action.

Mention this thing in the documentation or include this scope in the action.

**Comment by jplhomer** [comment]
I've added required scopes to the README; if there are additional steps needed, please submit a PR.

**Comment by teebu** [comment]
Instructions unclear, getting `Error: An API error occurred: not_in_channel` 

![image](https://user-images.githubusercontent.com/5531844/105553722-c85ad300-5cba-11eb-9979-f747ff8ed231.png)
