### ISSUE TITLE
Deprication Warning

### ISSUE THREAD

**Issue by johachi-dw** [voxmedia/github-action-slack-notify-build#9]
I get the following error message when I try to use this Github Action

```
(node:3136) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]An API error occurred: missing_scope
##[error]Node run failed with exit code 1
```

**Comment by jplhomer** [comment]
Hi @johachi-dw, that `DeprecationWarning` is expected and is a side effect of using the version of Node and the Slack Node client - you can likely ignore.

However, the legitimate error you have is:

```
An API error occurred: missing_scope
```

Could you verify that the Slack App token you're using has the correct access rights to whatever channel you're trying to post to?

**Comment by rbellamy** [comment]
What are the correct permissions? Nothing I've set seems to work, and I'm getting the same error.

**Comment by rbellamy** [comment]
I figured it out. The required permissions are `channels:join`, `channels:read`, `chat:write`, `groups:read`, `groups:write`.

**Comment by johachi-dw** [comment]
Thank you for your reply @jplhomer . I was able to solve this the same whay as @rbellamy !

@rbellamy , thank you for sharing your solution.

**Comment by mywristbands** [comment]
@rbellamy There's actually just up to 3 permissions that are required--see the [Slack App OAuth Scopes](https://github.com/voxmedia/github-action-slack-notify-build#slack-app-oauth-scopes) section in the README.
